api = "0.10"

[buildpack]
id = "luban-ci/python-uv"
version = "0.0.40"
name = "Python uv Buildpack"
homepage = "https://github.com/metasync/luban-ci"

[metadata]
[metadata.default-versions]
uv = "0.10.4"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
