# Test Configuration
# Inherits most settings from root Makefile.env
APP_NAME := luban-hello-world-py
REPO_URL := https://github.com/metasync/luban-hello-world-py.git
REVISION := main
TAG := 0.1.0
# GATEWAY_URL := https://webhook.luban.metasync.cc/push
GATEWAY_URL := https://webhook-luban.metasync.cc/push

# RBAC Verification
TEST_PROJECT := payment
TEST_ENV := snd
TEST_NAMESPACE := $(TEST_ENV)-$(TEST_PROJECT)
