# Test Configuration
# Inherits most settings from root Makefile.env
APP_NAME := luban-hello-world-py
REPO_URL := https://github.com/metasync/luban-hello-world-py.git
REVISION := $(shell git ls-remote $(REPO_URL) HEAD 2>/dev/null | awk '{print $$1}' | head -n 1)
TAG := 0.1.0
PROJECT_NAME := metasync
# GATEWAY_URL := https://webhook.luban.metasync.cc/push
GATEWAY_URL := https://webhook-luban.metasync.cc/push

# RBAC Verification
TEST_ENV := snd
TEST_NAMESPACE := $(TEST_ENV)-$(PROJECT_NAME)
