apiVersion: v1
kind: Secret
metadata:
  name: {{cookiecutter.image_pull_secret}}
  annotations:
    replicator.v1.mittwald.de/replicate-from: luban-ci/harbor-ro-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=
