apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{cookiecutter.namespace}}

resources:
  - ../../base
  - namespace.yaml
  - image-pull-secret.yaml

patches:
  - path: image-pull-secret-patch.yaml
