apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{cookiecutter.app_name}}-postgresql"
spec:
  serviceName: "{{cookiecutter.app_name}}-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: "{{cookiecutter.app_name}}-postgresql"
  template:
    metadata:
      labels:
        app: "{{cookiecutter.app_name}}-postgresql"
    spec:
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        runAsNonRoot: true
      containers:
        - name: postgres
          image: postgres:{{cookiecutter.postgres_version}}-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dagster-postgresql-secret
                  key: postgresql-password
            - name: POSTGRES_DB
              value: "dagster"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
