apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{cookiecutter.namespace}}

resources:
  - ../../base
  - namespace.yaml
  - promotion-shim.yaml
  - view-templates-binding.yaml

patches:
  - path: project-users-patch.yaml
