# Luban Provisioner Tooling Configuration
REGISTRY_SERVER ?= quay.io
REGISTRY_NAMESPACE ?= luban-ci
LUBAN_PROVISIONER_VERSION=0.3.10

# Template Rendering Configuration
TEMPLATES_DIR ?= templates/source
OUTPUT_DIR ?= /tmp/luban-rendered
DEFAULT_TEMPLATE ?= luban-dagster-dbt-starrocks-code-location-source-template
