apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: luban-pipeline-dispatcher-template
  namespace: luban-ci
spec:
  entrypoint: dispatch
  serviceAccountName: luban-ci-sa
  # Keep pods until the workflow is deleted
  podGC:
    strategy: OnWorkflowDeletion
  # Cleanup workflows
  ttlStrategy:
    secondsAfterCompletion: 86400
    secondsAfterSuccess: 3600
    secondsAfterFailure: 86400
  arguments:
    parameters:
      - name: repo_url
      - name: revision
      - name: app_name
      - name: git_ref
      - name: git_provider
        value: "github"
      - name: git_creds_secret
        value: "github-creds"
      - name: gitops_utils_image
        valueFrom:
          configMapKeyRef:
            name: luban-config
            key: gitops_utils_image

  templates:
  - name: dispatch
    inputs:
      parameters:
        - name: repo_url
        - name: revision
        - name: app_name
        - name: git_ref
        - name: git_provider
        - name: git_creds_secret
    container:
      image: "{{workflow.parameters.gitops_utils_image}}"
      # Inject configuration from luban-config in the local namespace (luban-ci)
      env:
        - name: REGISTRY_SERVER
          valueFrom:
            configMapKeyRef:
              name: luban-config
              key: registry_server
              optional: true
      command: [/usr/local/bin/argo_dispatch_ci_pipeline.sh]
      args:
        - "{{inputs.parameters.repo_url}}"
        - "{{inputs.parameters.revision}}"
        - "{{inputs.parameters.app_name}}"
        - "{{inputs.parameters.git_ref}}"
        - "{{inputs.parameters.git_provider}}"
        - "{{inputs.parameters.git_creds_secret}}"
