apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: namespace-provision-template
  namespace: luban-ci
spec:
  entrypoint: bootstrap-namespace
  serviceAccountName: luban-ci-sa
  arguments:
    parameters:
      - name: project_name
      - name: environment
      - name: git_organization
      - name: git_provider
        value: "azure"
        enum:
          - "github"
          - "azure"
          - "ado"
      - name: gitops_utils_image
        valueFrom:
          configMapKeyRef:
            name: luban-config
            key: gitops_utils_image

  templates:
  - name: bootstrap-namespace
    inputs:
      parameters:
      - name: project_name
      - name: environment
      - name: git_organization
      - name: git_provider
    steps:
    - - name: update-repo
        templateRef:
          name: infra-repo-update-template
          template: update-infra-cd-repo
        arguments:
          parameters:
          - name: repo_name
            value: "luban-infra-cd"
          - name: project_name
            value: "{{inputs.parameters.project_name}}"
          - name: env
            value: "{{inputs.parameters.environment}}"
          - name: git_organization
            value: "{{inputs.parameters.git_organization}}"
          - name: git_provider
            value: "{{inputs.parameters.git_provider}}"

    - - name: create-argo-app
        template: create-ns-app
        arguments:
          parameters:
          - name: project_name
            value: "{{inputs.parameters.project_name}}"
          - name: environment
            value: "{{inputs.parameters.environment}}"
          - name: git_organization
            value: "{{inputs.parameters.git_organization}}"
          - name: git_provider
            value: "{{inputs.parameters.git_provider}}"

  - name: create-ns-app
    inputs:
      parameters:
      - name: project_name
      - name: environment
      - name: git_organization
      - name: git_provider
    container:
      image: "{{workflow.parameters.gitops_utils_image}}"
      env:
        - name: GIT_SERVER
          valueFrom:
            configMapKeyRef:
              name: luban-config
              key: "{{inputs.parameters.git_provider}}_server"
        - name: GIT_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: luban-config
              key: "{{inputs.parameters.git_provider}}_base_url"
              optional: true
        - name: CLUSTER_MAP
          valueFrom:
            configMapKeyRef:
              name: luban-config
              key: cluster_map
        - name: CILIUM_EGRESS_GATEWAY_POLICY
          valueFrom:
            configMapKeyRef:
              name: luban-config
              key: cilium_egress_gateway_policy
              optional: true
      command: [/usr/local/bin/argocd_apply_namespace_infra_app.sh]
      args:
        - "{{inputs.parameters.environment}}"
        - "{{inputs.parameters.project_name}}"
        - "{{inputs.parameters.git_organization}}"
        - "{{inputs.parameters.git_provider}}"

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
