apiVersion: v1
kind: Secret
metadata:
  name: {{cookiecutter.app_name}}-secret
  annotations:
    replicator.v1.mittwald.de/replicate-from: luban-ci/{{cookiecutter.project_name}}-{{cookiecutter.app_name}}-secrets-snd
type: Opaque
stringData: {}
