apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-admin
  namespace: {{ cookiecutter.target_namespace }}
  annotations:
    workflows.argoproj.io/default-namespace: {{ cookiecutter.target_namespace }}
    workflows.argoproj.io/rbac-rule: "'{{ cookiecutter.admin_group }}' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-developer
  namespace: {{ cookiecutter.target_namespace }}
  annotations:
    workflows.argoproj.io/default-namespace: {{ cookiecutter.target_namespace }}
    workflows.argoproj.io/rbac-rule: "'{{ cookiecutter.developer_group }}' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"