apiVersion: v1
kind: Secret
metadata:
  name: project-admin.service-account-token
  namespace: {{ cookiecutter.target_namespace }}
  annotations:
    kubernetes.io/service-account.name: project-admin
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: project-developer.service-account-token
  namespace: {{ cookiecutter.target_namespace }}
  annotations:
    kubernetes.io/service-account.name: project-developer
type: kubernetes.io/service-account-token