apiVersion: v1
kind: ConfigMap
metadata:
  name: {{cookiecutter.app_name}}-config
data:
  APP_ENV: "prd"
{% if 'dbt' in cookiecutter.template_type %}
  DBT_TARGET: "production"
{% endif %}
{% if 'starrocks' in cookiecutter.template_type %}
  STARROCKS_ODS_DB: "{{cookiecutter.package_name}}_ods_prd"
  STARROCKS_DWD_DB: "{{cookiecutter.package_name}}_dwd_prd"
  STARROCKS_DWS_DB: "{{cookiecutter.package_name}}_dws_prd"
  STARROCKS_DB: "{{cookiecutter.package_name}}_dws_prd"
{% endif %}
