apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-observability
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{cookiecutter.otel_exporter_otlp_endpoint}}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{cookiecutter.otel_exporter_otlp_protocol}}"
  # OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer <apm_token>"
  OTEL_RESOURCE_ATTRIBUTES: "{{cookiecutter.otel_resource_attributes}}"
  OTEL_SERVICE_NAME: "{{ cookiecutter.otel_service_name or cookiecutter.project_name ~ '-' ~ cookiecutter.app_name }}"
  OTEL_TRACES_EXPORTER: "none"
  OTEL_METRICS_EXPORTER: "none"
