apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-runner-kpack-admin
  namespace: {{ cookiecutter.target_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: luban-kpack-admin
subjects:
  - kind: ServiceAccount
    name: workflow-runner
    namespace: {{ cookiecutter.target_namespace }}
