apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
  namespace: luban-ci
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    orgwebhook:
      organizations:
        - "metasync"
      webhook:
        endpoint: "/github/push"
        port: "12000"
        method: "POST"
        url: "https://webhook.luban.k8s.orb.local/github/push"
      events:
        - "*"
      webhookSecret:
        name: webhook-secret
        key: secret
      insecure: false
      active: true
      contentType: json
