apiVersion: v1
kind: Secret
metadata:
  name: ado-ssh-creds
  annotations:
    replicator.v1.mittwald.de/replicate-from: luban-ci/ado-ssh-creds
    kpack.io/git: {{ cookiecutter.ado_ssh_host }}
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: placeholder
