apiVersion: v1
kind: Secret
metadata:
  name: azure-ssh-creds
  annotations:
    replicator.v1.mittwald.de/replicate-from: luban-ci/azure-ssh-creds
    kpack.io/git: ssh.dev.azure.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: placeholder

