apiVersion: v1
kind: Secret
metadata:
  name: harbor-creds
  annotations:
    replicator.v1.mittwald.de/replicate-from: luban-ci/harbor-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=

