apiVersion: v1
kind: Secret
metadata:
  name: luban-ca-cert
  annotations:
    replicator.v1.mittwald.de/replicate-from: luban-ci/luban-ca-cert
type: service.binding/ca-certificates
stringData:
  type: ca-certificates
  provider: luban-ci
  ca.crt: placeholder
