apiVersion: v1
kind: Secret
metadata:
  name: uv-mirror-netrc
  annotations:
    replicator.v1.mittwald.de/replicate-from: luban-ci/uv-mirror-netrc
type: service.binding/netrc
stringData:
  type: netrc
  provider: luban-ci
  netrc: placeholder
