apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{cookiecutter.app_name}}-sa
roleRef:
  kind: Role
  name: dagster-role
  apiGroup: rbac.authorization.k8s.io
